# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: minhinc
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: netify
service: supbase-be

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1 # Or your preferred AWS region
  environment:
    REDDIT_CLIENT_ID: ${env:REDDIT_CLIENT_ID}
    REDDIT_CLIENT_SECRET: ${env:REDDIT_CLIENT_SECRET}
    REDDIT_USERNAME: ${env:REDDIT_USERNAME}
    REDDIT_PASSWORD: ${env:REDDIT_PASSWORD}
    REDDIT_QUEST_LOG_THREAD_ID: ${env:REDDIT_QUEST_LOG_THREAD_ID}
    REDDIT_REDIRECT_URI: ${env:REDDIT_REDIRECT_URI}
    ALGOD_API_TOKEN: ${env:ALGOD_API_TOKEN}
    ALGOD_SERVER_URL: ${env:ALGOD_SERVER_URL}
    A_MNEMONIC: ${env:A_MNEMONIC}
    INTERNAL_API_SECRET: ${env:INTERNAL_API_SECRET}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}
    FRONTEND_URL: ${env:FRONTEND_URL}
    API_URL: ${env:API_URL}
    ELEVENLABS_VOICE_ID: ${env:ELEVENLABS_VOICE_ID}
    ELEVENLABS_API_KEY: ${env:ELEVENLABS_API_KEY}
    TAVUS_API_KEY: ${env:TAVUS_API_KEY}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    STRIPE_STUDENT_PRO_PRODUCTID: ${env:STRIPE_STUDENT_PRO_PRODUCTID}
    STRIPE_STUDENT_VIP_PRODUCTID: ${env:STRIPE_STUDENT_VIP_PRODUCTID}
    STRIPE_PRO_PRODUCTID: ${env:STRIPE_PRO_PRODUCTID}
    STRIPE_VIP_PRODUCTID: ${env:STRIPE_VIP_PRODUCTID}
    STRIPE_PRO_TRIAL_PRICE_ID: ${env:STRIPE_PRO_TRIAL_PRICE_ID}
    STRIPE_PRO_MONTHLY_PRICE_ID: ${env:STRIPE_PRO_MONTHLY_PRICE_ID}
    STRIPE_PRO_ANNUAL_ID: ${env:STRIPE_PRO_ANNUAL_ID}
    STRIPE_VIP_TRIAL_PRICE_ID: ${env:STRIPE_VIP_TRIAL_PRICE_ID}
    STRIPE_VIP_MONTHLY_PRICE_ID: ${env:STRIPE_VIP_MONTHLY_PRICE_ID}
    STRIPE_VIP_ANNUAL_ID: ${env:STRIPE_VIP_ANNUAL_ID}
    STRIPE_STUDENT_PRO_MONTHLY_ID: ${env:STRIPE_STUDENT_PRO_MONTHLY_ID}
    STRIPE_STUDENT_PRO_ANNUAL_ID: ${env:STRIPE_STUDENT_PRO_ANNUAL_ID}
    STRIPE_STUDENT_VIP_TRIAL_PRICE_ID: ${env:STRIPE_STUDENT_VIP_TRIAL_PRICE_ID}
    STRIPE_STUDENT_VIP_MONTHLY_ID: ${env:STRIPE_STUDENT_VIP_MONTHLY_ID}
    STRIPE_STUDENT_VIP_ANNUAL_ID: ${env:STRIPE_STUDENT_VIP_ANNUAL_ID}

functions:
  api:
    handler: app.handler # This will point to your exported Express app
    events:
      - httpApi: '*' # This creates a proxy that forwards ALL requests to your app